config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  devise_for :users, controllers: {omniauth_callbacks: 'oauth'}

  namespace :user do
    get '/oauth_adding_email', to: 'emails#new'
    post '/oauth_adding_email', to: 'emails#create'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only:%i[index show create update destroy], shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :vote
    end
  end

  concern :commentable do
    resource :comments, only: %i[create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: %i[create update destroy] do
      member do
        patch :best
      end
    end
  end

  resources :files, only: %i[destroy]

  resources :users do
    resources :rewards, shallow: true, only: %i[index show]
  end

  resources :subscriptions, only: %i[create]
  delete '/subscriptions', to: 'subscriptions#destroy'

  get '/search', to: 'search#result'

  root to: 'questions#index'

  mount ActionCable.server => '/cable'

  authenticate :user, lambda {|user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Authorable
  include Linkable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true

  after_create :subscribe

  private

  def subscribe
    subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource class: Question

  expose :questions, ->{ Question.all.order(created_at: :desc) }
  expose :question, -> { params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new }

  def index
    render json: questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: question
  end

  def create
    @question = current_resource_owner.author_questions.new(question_params)
    if @question.save
      render json: @question
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, question
    if question.update(question_params)
      render json: question
    else
      render json: { errors: question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, question
    question.destroy
    render json: {}, status: :ok
  end

  private

  def question_params
    params.require(:question).permit(:title,
                                     :body,
                                     links_attributes: [:name, :url, :id, :_destroy]
                                     )
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  include Voted

  before_action -> { question.links.build }, only: [:new, :create]

  after_action :pub_question, only: :create

  expose :questions, ->{ Question.all.order(created_at: :desc) }
  expose :question, -> { params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new }

  authorize_resource

  def create
    @question = current_user.author_questions.new(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])
    authorize! :update, @question
    @question.update(question_params)
  end

  def destroy
    authorize! :destroy, question
    question.destroy
    redirect_to questions_path, notice: 'Your question was successfully deleted.'
  end

  private

  def pub_question
    return if @question.errors.any?
    ActionCable.server.broadcast "questions",
      ApplicationController.render(
                            partial: 'questions/question_simple',
                            locals: { question: @question }
      )
  end

  def question_params
    params.require(:question).permit(:title,
                                     :body,
                                     :vote,
                                     Voted::STRONG_PARAMS,
                                     files: [],
                                     links_attributes: [:name, :url, :id, :_destroy],
                                     reward_attributes: [:title, :image],
                                     )
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
h1= question.title
p= question.body

= render 'shared/votes', resource: question

- if can?(:create, Subscription)
  h6
    = "Subscription on question: "
    span = check_box_tag 'subscribe', nil, current_user&.get_sub_on_question(question).present?, class: 'subscribe'

- if can?(:update, question)
  ul.question_actions *{:class => "list-inline"}
    li.list-inline-item= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    = form_with model: question, class: 'hidden', html: {id: "edit-question-#{question.id}"} do |f|
      .question_errors= render 'shared/errors', resource: question
      p
        = f.label :title
        = f.text_field :title, class: "form-control"
      p
        = f.label :body
        = f.text_area :body, class: "form-control"
      p
        = f.label :files
        br
        = f.file_field :files, multiple: true, direct_upload: true

      - question.links.build if question.links.empty?
      = render 'shared/links_form', form: f

      p = f.submit 'Save'
    - if can?(:destroy, question)
      li.list-inline-item= link_to 'Delete', question_path(question), method: :delete, data: { confirm: 'Are your sure?' }

- if question.links.any? && question.links.first.persisted?
  = render 'shared/links', links: question.links

- if question.files.attached?
  = render 'shared/files', files: question.files

- unless question.reward.nil?
  / TODO можно ли вставить ссылку в строку без html_safe?
  blockquote.blockquote= "Reward assigned #{link_to  question.reward.title, question.reward}!".html_safe

app/views/questions/_question_simple.html.slim
li.question= link_to question.title, question

app/views/questions/index.html.slim
h4
  - if can?(:create, Question)
    p= link_to 'Ask question', new_question_path

  ul.questions
    = render partial: 'question_simple', collection: questions, :as => :question

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

p= form_with model: question, local: true do |f|
  = f.label :title
  = f.text_field :title, class: "form-control"
  = f.label :body
  = f.text_area :body, class: "form-control"

  p
    = f.label :files
    br
    = f.file_field :files, multiple: true

    = render 'shared/links_form', form: f

    - question.build_reward
    = render 'shared/reward_form', form: f

  p = f.submit 'Ask'

app/views/questions/show.html.slim
- cache [question, current_user]
  .question_box *{class: "border rounded border-primary mb-5 px-3", data: { 'question-id': question.id }}
    = render question


    div[id="comments-question-#{question.id}" class="comments"]
      - if can?(:create, Comment)
        = render 'comments/new', comment: question.comments.new

      ul
        = render partial: 'comments/comment', collection: question.comments.select(&:persisted?), :as => :comment

  ul.question_answers
    = render question.answers.with_attached_files

  - if can?(:create, Answer)
    = render 'answers/new', answer: question.answers.new

app/views/questions/update.js.erb
var $questionItem = $('.question_box');

<% if @question.errors.present? %>
  $questionItem
      .find('.question_errors')
      .html('<%= render 'shared/errors', resource: @question %>');
<% else %>
  $questionItem.html('<%= j render @question %>');
<% end %>