config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  devise_for :users, controllers: {omniauth_callbacks: 'oauth'}

  namespace :user do
    get '/oauth_adding_email', to: 'emails#new'
    post '/oauth_adding_email', to: 'emails#create'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only:%i[index show create update destroy], shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :vote
    end
  end

  concern :commentable do
    resource :comments, only: %i[create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: %i[create update destroy] do
      member do
        patch :best
      end
    end
  end

  resources :files, only: %i[destroy]

  resources :users do
    resources :rewards, shallow: true, only: %i[index show]
  end

  resources :subscriptions, only: %i[create]
  delete '/subscriptions', to: 'subscriptions#destroy'

  get '/search', to: 'search#result'

  root to: 'questions#index'

  mount ActionCable.server => '/cable'

  authenticate :user, lambda {|user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question, touch: true
  belongs_to :answer, optional: true

  has_one_attached :image

  validates :title, presence: true
  validate :attached_type

  private

  def attached_type
    types = ['jpeg', 'png', 'gif']

    if image.attached?
      errors.add(:image, ": Available file types for reward: #{types.join(', ')}") unless image.content_type =~ /^image\/(#{types.join('|')})/
    end

  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController

  expose :reward, ->{ Reward.find(params[:id]) }
  expose :user
  expose :rewards, -> { user.rewards }

  authorize_resource

end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/index.html.slim
.rewards
  - rewards.each do |reward|
    .reward *{:class => "col-6 col-md-2 border rounded border-primary mb-5 px-3 "}
      h2= link_to reward.title, reward
      h4= link_to reward.question.title, reward.question
      - if reward.image.attached?
        p.image= image_tag url_for(reward.image), height: '150px'

app/views/rewards/show.html.slim
.col-6.col-md-4
  - if current_user
    h1= link_to 'See My Rewards', user_rewards_path(current_user)

  .reward *{:class => "border rounded border-primary mb-5 px-3 "}
    h1= reward.title
    h2= link_to reward.question.title, reward.question
    - if reward.image.attached?
      p.image= image_tag url_for(reward.image), height: '400px'