config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  use_doorkeeper
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  devise_for :users, controllers: {omniauth_callbacks: 'oauth'}

  namespace :user do
    get '/oauth_adding_email', to: 'emails#new'
    post '/oauth_adding_email', to: 'emails#create'
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only:%i[index show create update destroy], shallow: true
      end
    end
  end

  concern :votable do
    member do
      patch :vote
    end
  end

  concern :commentable do
    resource :comments, only: %i[create]
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, concerns: [:votable, :commentable], shallow: true, only: %i[create update destroy] do
      member do
        patch :best
      end
    end
  end

  resources :files, only: %i[destroy]

  resources :users do
    resources :rewards, shallow: true, only: %i[index show]
  end

  resources :subscriptions, only: %i[create]
  delete '/subscriptions', to: 'subscriptions#destroy'

  get '/search', to: 'search#result'

  root to: 'questions#index'

  mount ActionCable.server => '/cable'

  authenticate :user, lambda {|user| user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Authorable
  include Linkable
  include Votable
  include Commentable

  belongs_to :question, touch: true
  has_one :reward

  validates :body, presence: true

  has_many_attached :files

  default_scope { order(best:  :desc, created_at: :desc) }
  scope :get_best, -> { where(best: true) }

  after_create_commit :send_notice

  def make_best
    transaction do
      question.answers.get_best.take&.update!(best: false)
      update!(best: true)
      update!(reward: question.reward) if question.reward
    end
  end

  private

  def send_notice
    NotifyNewAnswerJob.perform_later(self)
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :authenticate_user!

  include Voted

  expose :answers, ->{ Answer.all }
  expose :answer, -> { params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new }
  expose :question

  authorize_resource

  after_action :pub_answer, only: :create

  def create
    @answer = question.answers.new(answer_params)
    @answer.author = current_user
    @answer.save
  end

  def update
    authorize! :update, answer
    answer.update(answer_params)
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
  end

  def best
    authorize! :best, answer
    answer.make_best
  end

  private

  def answer_params
    params.require(:answer).permit(:body,
                                   Voted::STRONG_PARAMS,
                                   files: [],
                                   links_attributes: [:name, :url, :id, :_destroy]
                                  )
  end

  def pub_answer
    return if @answer.errors.any?

    AnswersChannel.broadcast_to(
      @answer.question,
      answer: @answer,
      files: @answer.files.map { |file| { id: file.id, name: file.filename.to_s, url: url_for(file) } },
      links: @answer.links.select(&:persisted?)
    )
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource class: Answer

  expose :question
  expose :answers, ->{ question.answers }
  expose :answer, -> { params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new }

  def index
    render json: answers, each_serializer: AnswersSerializer
  end

  def show
    render json: answer
  end

  def create
    @answer = question.answers.new(answer_params)
    @answer.author = current_resource_owner

    if @answer.save
      render json: @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, answer
    if answer.update(answer_params)
      render json: answer
    else
      render json: { errors: answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
    render json: {}, status: :ok
  end


  private

  def answer_params
    params.require(:answer).permit(:body,
                                   links_attributes: [:name, :url, :id, :_destroy]
    )
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache [answer, current_user]
    li.answer *{:class => "border-left mb-3 px-4 #{"best" if answer.best}"} id="answer-#{answer.id}"

      - if answer.best?
        p.best
          = octicon "mortar-board", :height => 48
          = " This is best answer!"

      p= answer.body

      = render 'shared/votes', resource: answer

      ul.answer_actions *{:class => "list-inline mb-2"}
        - if can?(:best, answer)
          li.list-inline-item= link_to 'make best?', best_answer_path(answer), method: :patch, class: "best-answer-link", data: {answer_id: answer.id}, remote: true


        - if can?(:destroy, answer)
          li.list-inline-item= link_to 'Delete', answer_path(answer), remote: true, method: :delete, data: {confirm: 'Are your sure?'}
        - if can?(:update, answer)
          li.list-inline-item= link_to 'Edit', '#', class: 'edit-answer-link', data: {answer_id: answer.id}

          = form_with model: answer, class: 'hidden', html: {id: "edit-answer-#{answer.id}"} do |f|
            .answer_errors= render 'shared/errors', resource: answer
            p
              = f.label :body, 'Your answer'
              = f.text_area :body, class: "form-control"
            p
              = f.label :files
              br
              = f.file_field :files, multiple: true, direct_upload: true

            - answer.links.build if answer.links.empty?
            = render 'shared/links_form', form: f

            p = f.submit 'Save'

      - if answer.links.any? && answer.links[0].persisted?
        = render 'shared/links', links: answer.links

      - if answer.files.attached?
        = render 'shared/files', files: answer.files

      div[id="comments-answer-#{answer.id}" class="comments"]
        - if can?(:create, Comment)
          = render 'comments/new', comment: answer.comments.new

        ul
          = render partial: 'comments/comment', collection: answer.comments.select(&:persisted?), :as => :comment

app/views/answers/_new.html.slim
.new-answer *{:class => "border rounded border-info mb-5 p-3"}
  h2= "Add your answer:"
  .answer-errors
    = render 'shared/errors', resource: @answer

  = form_with model: [question, answer], class: 'new-answer' do |f|
    p
      = f.label :body
      = f.text_area :body, class: "form-control"

    p
      = f.label :files
      br
      = f.file_field :files, multiple: true, direct_upload: true

    - answer.links.build if answer.links.empty?
    = render 'shared/links_form', form: f

    = f.submit 'Reply'

app/views/answers/best.js.erb
var $answerItem = $('#answer-<%= answer.id %>');

<% if answer.errors.present? %>
  $answerItem
      .find('.answer_errors')
      .html('<%= render 'shared/errors', resource: answer %>');
<% else %>
  $answerItem.parent().html('<%= j render answer.question.answers %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.question_answers').prepend('<%= j render @answer %>');
  newAnswer = $('.new-answer')
  newAnswer.find('#answer_body').val('');
  newAnswer.find('#answer_links_attributes_0_name').val('');
  newAnswer.find('#answer_links_attributes_0_url').val('');
  newAnswer.find('#answer_files').val('').removeAttr("disabled");
  newAnswer.find('input[type="hidden"][name="answer[files][]"]').remove();
  newAnswer.find('.new_link').not(':first').remove();
<% end %>

app/views/answers/destroy.js.erb
$('.notice').html('Your answer was successfully deleted.');
$('#answer-<%= answer.id %>').remove();

app/views/answers/update.js.erb
var $answerItem = $('#answer-<%= answer.id %>');

<% if answer.errors.present? %>
  $answerItem
      .find('.answer_errors')
      .html('<%= render 'shared/errors', resource: answer %>');
<% else %>
  $answerItem.replaceWith('<%= j render answer %>');
<% end %>